version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: demo_postgres
    environment:
      POSTGRES_USER: omer
      POSTGRES_PASSWORD: omer
      POSTGRES_DB: demo_db
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: